version: '3.8'
services:
  api:
    container_name: befv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - pullapp-network

networks:
  pullapp-network:
    driver: bridge